const TAGS = {
  spellDamage: "Spell Damage",
  physicalAttack: "Physical Damage",
  cooldown: "CDR",
  attackSpeed: "Attack Speed",
  mobility: "Mobility",
  movementSpeed: "Movement Speed",
  burst: "Burst",
  bruiser: "Bruiser",
  tank: "Tank",
  sustain: "Sustain",
  waveClear: "Wave Clear",
  basicAttack: "Basic Attack",
  crit: "Crit",
  manaRegen: "Mana Regen",
  antiHeal: "Anti-Heal",
  shield: "Shield",
  mana: "Mana",
  physicalPenetration: "Physical Penetration",
  spellPenetration: "Spell Penetration",
  defense: "Defense",
  support: "Support",
  jungle: "Jungle",
  spellDefense: "Spell Defense",
  physicalDefense: "Physical Defense",
  tenacity: "Tenacity",
  toughness: "Toughness",
  healing: "Healing",
  lifesteal: "Lifesteal",
  spellVamp: "Spell Vamp",
  physicalLifesteal: "Physical Lifesteal",
  cleanse: "Cleanse",
  vision: "Vision",
  gold: "Gold",
  maxHp: "Max HP",
  maxMana: "Max Mana",
  critChance: "Crit Chance",
  critDamage: "Crit Damage",
  slow: "Slow",
  healthBasedDamage: "Health-Based Damage",
  shieldPiercing: "Shield-Piercing",
  execute: "Execute",
  onHit: "On-Hit",
  control: "Control",
  physicalDamageReduction: "Physical Damage Reduction",
  healthRegen: "Health Regen",
  physicalPierce: "Physical Pierce",
  spellPierce: "Spell Pierce",
  active: "Active",
  aura: "Aura",
  invulnerability: "Invulnerability",
  outOfCombatMS: "Out of Combat MS",
  bonusDamage: "Bonus Damage",
  summonerSpellCDR: "Summoner Spell CDR",
  damageReduction: "Damage Reduction"
};